- name: install desktop environment KDE
  apt:
    pkg:
      - kde-standard
      - kde-plasma-desktop
    state: present 
    install_recommends: yes
  when: linux_desktop == 'kde'
  become: yes

- name: install desktop environment Cinnamon
  apt:
    pkg:
      - cinnamon-core
      - libgl1-mesa-dri 
      - x11-xserver-utils
      - gnome-terminal
      - lightdm
    state: present 
    install_recommends: no
  when: linux_desktop == 'cinnamon'
  become: yes

- name: install desktop environment Gnome
  apt:
    pkg:
      - gnome
    state: present 
    install_recommends: no
  when: linux_desktop == 'gnome'
  become: yes

- name: install desktop environment Mate
  apt:
    pkg:
      - mate-desktop-environment
      - lightdm
    state: present 
    install_recommends: no
  when: linux_desktop == 'mate'
  become: yes

- name: install desktop environment Xfce
  apt:
    pkg:
      - xfce4
      - xfce4-goodies
      - lightdm
    state: present 
    install_recommends: no
  when: linux_desktop == 'xfce'
  become: yes

- name: install Xorg
  apt: 
    pkg:
      - xorg
    state: present
  become: yes